# Generated by Django 4.0 on 2022-06-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ('id',), 'verbose_name': 'Mi Departamento', 'verbose_name_plural': 'Areas de la empresas'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'shor_name')},
        ),
    ]
