# Generated by Django 4.0 on 2022-10-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='anulate',
            field=models.BooleanField(default=False, verbose_name='Anulado'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='shor_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre Corto'),
        ),
    ]
