# Generated by Django 4.0 on 2022-06-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=20, verbose_name='Apellido')),
                ('job', models.CharField(choices=[('0', 'Otro'), ('1', 'Contador'), ('2', 'Administrador'), ('3', 'Economista')], max_length=1, verbose_name='Puesto')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
            ],
        ),
    ]
