# Generated by Django 4.0 on 2022-06-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_rename_hablidades_habilidades_habilidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='hablidades',
        ),
        migrations.DeleteModel(
            name='Habilidades',
        ),
    ]
