# Generated by Django 4.0 on 2022-06-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_remove_empleado_hablidades_delete_habilidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidades',
                'verbose_name_plural': 'Habilidades Empleados',
            },
        ),
        migrations.AlterField(
            model_name='empleado',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='persona.Habilidades'),
        ),
    ]
