# Generated by Django 4.0 on 2022-06-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_habilidades_alter_empleado_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'ordering': ('id',), 'verbose_name': 'Habilidades', 'verbose_name_plural': 'Habilidades Empleados'},
        ),
    ]
