# Generated by Django 4.0 on 2022-07-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
    ]
