# Generated by Django 4.0 on 2022-11-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0012_empleado_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Otro'), ('1', 'Contador'), ('2', 'Administrador'), ('3', 'Vendedor'), ('4', 'RR.HH')], max_length=1, verbose_name='Puesto'),
        ),
    ]
